development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: campaign_monitor_development
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: campaign_monitor_test
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: campaign_monitor 
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock
